[package]
name = "subspace-metrics"
version = "0.1.0"
edition = "2021"
authors = [
    "Shamil Gadelshin <shamilgadelshin@gmail.com>"
]
description = "Metrics for Subspace Network"
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/subspace/subspace"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
actix-web = "4.5.1"
prometheus = { version = "0.13.0", default-features = false }
prometheus-client = "0.22.0"
tracing = "0.1.40"
