FROM ubuntu:20.04

ARG RUSTC_VERSION=nightly-2024-01-19
ARG PROFILE=production
ARG TARGET_ARCH=x86_64-unknown-linux-gnu

# Ensure binary compatibility with older CPUs such as Xeon E5
# Add flags to disable certain CPU features not supported by Xeon E5
ENV RUSTFLAGS="-C target-cpu=x86-64 -C target-feature=-avx,-avx2,+sse4.1"
# Workaround for https://github.com/rust-lang/cargo/issues/10583
ENV CARGO_NET_GIT_FETCH_WITH_CLI=true
# Incremental compilation here isn't helpful
ENV CARGO_INCREMENTAL=0

WORKDIR /code

# Install necessary packages
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        ca-certificates \
        protobuf-compiler \
        curl \
        git \
        llvm \
        clang \
        automake \
        libtool \
        pkg-config \
        make && \
    # Install Rust toolchain
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain $RUSTC_VERSION && \
    # Add wasm target
    /root/.cargo/bin/rustup target add wasm32-unknown-unknown

# Prepare the source code
COPY .cargo /code/.cargo
COPY Cargo.lock /code/Cargo.lock
COPY Cargo.toml /code/Cargo.toml
COPY rust-toolchain.toml /code/rust-toolchain.toml
COPY crates /code/crates
COPY domains /code/domains
COPY orml /code/orml
COPY shared /code/shared
COPY test /code/test

# Build the application
RUN /root/.cargo/bin/cargo -Zgitoxide -Zgit build \
        --locked \
        -Z build-std \
        --profile $PROFILE \
        --bin subspace-farmer \
        --target $TARGET_ARCH && \
    # Move the binary to a known location
    mv target/$TARGET_ARCH/$PROFILE/subspace-farmer subspace-farmer && \
    # Clean up build artifacts to reduce image size
    rm -rf target

# Start the final stage with a fresh Ubuntu image
FROM ubuntu:20.04

# Copy compiled binary from builder image
COPY --from=0 /code/subspace-farmer /subspace-farmer

# Prepare environment for non-root execution.
RUN mkdir /var/subspace && chown nobody:nogroup /var/subspace

VOLUME /var/subspace
USER nobody:nogroup

ENTRYPOINT ["/subspace-farmer"]